return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local config = require("nvim-treesitter.configs")
		config.setup({
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"c",
				"cpp",
				"make",
				"lua",
				"dockerfile",
				"python",
				"vim",
				"vimdoc",
				"json",
				"jsonc",
				"toml",
				"yaml",
				"query",
				"gitcommit",
				"gitignore",
				"regex",
				"diff",
				"bash",
				"markdown",
				"markdown_inline",
				"bibtex",
				"rust",
				"typescript",
				"javascript",
				"html",
				"css",
				"typst",
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		})
	end,
}
