import = ["~/dotfiles/.config/alacritty/catppuccin-mocha.toml"]


[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
blur = true
opacity = 1.0
option_as_alt = "Both"

[font]

normal.family = "JetBrainsMonoNerdFont"
size = 12

[cursor.style]
shape = "Block"

[selection]

save_to_clipboard = true
