import = ["~/dotfiles/.config/alacritty/catppuccin-mocha.toml"]

[env] 
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.9

blur = true

option_as_alt = "Both"

[font]

normal.family = "JetBrainsMonoNerdFont"
size = 12

[colors]

primary.background = "#000000"

[selection]

save_to_clipboard = true

